baseURL = 'https://flagzeta.org/'
languageCode = 'en-us'
title = "Federico Marani"
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
staticDir = ["../static"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[params]
  mainSections = ["articles"]

  [params.author]
    name = 'Federico Marani'
    email = 'me@federicomarani.com'

[module]
[[module.mounts]]
  source = '../posts'
  target = 'content/articles'

[[module.mounts]]
  source = '../til'
  target = 'content/til'
